### Jobs list
GET http://{{host}}:{{port}}/api/jobs
Accept: application/json

###
POST http://{{host}}:{{port}}/api/jobs
Content-Type: application/json

{
  "payload" : "hello world 123",
  "callback_url" : "https://webhook.site/<your token>"
}

###
